# Example: Override respecConfig for W3C deployment and validators.
name: Echidna Auto-publish
on:
  pull_request: {}
  push:
    branches: [main]
jobs:
  main:
    name: Echidna Auto-publish WD
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: w3c/spec-prod@v2
        with:
          TOOLCHAIN: respec
          SOURCE: spec/index.html
          W3C_ECHIDNA_TOKEN: ${{ secrets.ECHIDNA_TOKEN }}
          W3C_WG_DECISION_URL: https://www.w3.org/2022/11/09-rch-minutes#r03
          W3C_BUILD_OVERRIDE: |
            specStatus: WD
            shortName: rdf-canon
